#!/usr/bin/env python3
"""Assemble set4/set5 corpus from candidates/curation.json:
  - copy each source .kicad_pcb into sources/github_setN/<slug>.kicad_pcb
  - try to fetch the sibling .kicad_pro from the repo (best effort)
  - write manifest_set4.json (existing fpga_sdram + new) and manifest_set5.json
  - regenerate prep_set4.sh and prep_set5.sh with a full MAP array
Run with plain python3 (the prep step itself uses KiCad's python separately)."""
import json, os, shutil, subprocess
from pathlib import Path

STRESS = Path.home() / "Documents/kicad_stress_test"
CAND = STRESS / "sources/candidates"
STRESS_TESTS = Path("/Users/andy/Documents/KiCadRoutingTools/tests/stress")
cur = json.load(open(CAND / "curation.json"))

TIER_PKG = {"easy": "2-layer,MCU", "medium": "4-layer,USB,MCU", "hard": "BGA,FPGA/SoC,high-speed"}

def fetch_pro(raw_url, dest):
    if not raw_url or not raw_url.endswith(".kicad_pcb"): return False
    pro_url = raw_url[:-len(".kicad_pcb")] + ".kicad_pro"
    r = subprocess.run(["curl", "-sL", "--fail", pro_url, "-o", str(dest)], capture_output=True)
    if r.returncode == 0 and dest.exists() and dest.stat().st_size > 20:
        return True
    if dest.exists(): dest.unlink()
    return False

by_set = {4: [], 5: []}
for b in cur: by_set[b["set"]].append(b)

for s in (4, 5):
    src_dir = STRESS / f"sources/github_set{s}"
    src_dir.mkdir(parents=True, exist_ok=True)
    manifest = []
    # set4 keeps only its ORIGINAL entry (fpga_sdram). Entries WITHOUT a
    # short_name were not generated by this script -> idempotent across re-runs.
    if s == 4:
        existing = json.load(open(STRESS_TESTS / "manifest_set4.json"))
        manifest.extend([e for e in existing if "short_name" not in e])
    mapping = []  # (short_name, filename_fragment) for prep MAP
    pros = 0
    for b in sorted(by_set[s], key=lambda x: (x["tier"], x["name"])):
        slug = b["slug"]
        fn = f"{slug}.kicad_pcb"
        dst = src_dir / fn
        src_path = b["src"] if os.path.isabs(b["src"]) else str(CAND / b["src"])
        shutil.copy(src_path, dst)
        got_pro = fetch_pro(b["raw_url"], src_dir / f"{slug}.kicad_pro")
        pros += 1 if got_pro else 0
        manifest.append({
            "set": f"set{s}", "repo": b["repo"], "path": b["path"],
            "file": str(dst), "raw_url": b["raw_url"], "github_url": b["github_url"],
            "size_kb": dst.stat().st_size // 1024, "layers_est": b["layers"],
            "footprints": b["footprints"], "routable_nets": b["routable_nets"],
            "tier": b["tier"], "packages": TIER_PKG.get(b["tier"], "?"),
            "license": "see repo", "short_name": b["name"], "note": b["note"] or b["repo"],
        })
        mapping.append((b["name"], slug))
    json.dump(manifest, open(STRESS_TESTS / f"manifest_set{s}.json", "w"), indent=2)
    # regenerate prep_setN.sh with the MAP
    map_lines = "\n".join(f'  "{n}|{frag}"' for n, frag in mapping)
    prep = f'''#!/bin/bash
# Normalize+strip every set-{s} board (one pcbnew process each, segfault-safe).
# Reuses prep_set2.py (generic: <src> <routed_dst> <stripped_dst>).
#   stripped, unrouted boards -> boards_unrouted_set{s}/
#   normalized routed reference + .kicad_pro -> boards_set{s}/
# Auto-generated by sources/assemble_corpus.py. Sources are modern KiCad (v6+).
set -u
SELF="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
STRESS="${{STRESS_DIR:-$HOME/Documents/kicad_stress_test}}"
SRC="$STRESS/sources/github_set{s}"
KPY="${{KICAD_PYTHON:-/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3}}"
PREP="$SELF/prep_set2.py"
mkdir -p "$STRESS/boards_unrouted_set{s}" "$STRESS/boards_set{s}"

# short-name | source-filename-fragment (unique within github_set{s}/)
MAP=(
{map_lines}
)

for entry in "${{MAP[@]}}"; do
  IFS='|' read -r name frag <<< "$entry"
  srcfile=$(find "$SRC" -maxdepth 1 -name '*.kicad_pcb' -name "*${{frag}}*" | head -1)
  if [ -z "$srcfile" ]; then echo "MISS $name (frag '$frag')"; continue; fi
  echo "== $name <- $(basename "$srcfile")"
  "$KPY" "$PREP" "$srcfile" "$STRESS/boards_set{s}/$name.kicad_pcb" \\
         "$STRESS/boards_unrouted_set{s}/$name.kicad_pcb" 2>/dev/null || echo "  FAIL $name"
  profile="${{srcfile%.kicad_pcb}}.kicad_pro"
  [ -f "$profile" ] && cp "$profile" "$STRESS/boards_set{s}/$name.kicad_pro"
done
echo "Done. stripped -> boards_unrouted_set{s}/ ; routed reference -> boards_set{s}/"
'''
    (STRESS_TESTS / f"prep_set{s}.sh").write_text(prep)
    os.chmod(STRESS_TESTS / f"prep_set{s}.sh", 0o755)
    print(f"set{s}: {len(mapping)} new boards -> github_set{s}/ ; sibling .kicad_pro fetched: {pros}/{len(mapping)} ; manifest={len(manifest)} entries ; prep_set{s}.sh regenerated")
print("done")
