#!/bin/bash
# Normalize+strip every set-5 board (one pcbnew process each, segfault-safe).
# Reuses prep_set2.py (generic: <src> <routed_dst> <stripped_dst>).
#   stripped, unrouted boards -> boards_unrouted_set5/
#   normalized routed reference + .kicad_pro -> boards_set5/
# Auto-generated by sources/assemble_corpus.py. Sources are modern KiCad (v6+).
set -u
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STRESS="${STRESS_DIR:-$HOME/Documents/kicad_stress_test}"
SRC="$STRESS/sources/github_set5"
KPY="${KICAD_PYTHON:-/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3}"
PREP="$SELF/prep_set2.py"
mkdir -p "$STRESS/boards_unrouted_set5" "$STRESS/boards_set5"

# short-name | source-filename-fragment (unique within github_set5/)
MAP=(
  "daplink|andychang__daplink"
  "ft2232h_jtag|thecasterian__ft2232h-jtag-uart"
  "nrfmicro|joric__nrfmicro__nrfmicro"
  "teensy4_galvos|weiwei__teensy4-galvos"
  "usbgpib|xyphro__usbgpib"
  "apple1|jgw4__apple1_mainboard"
  "dilemma|Bastardkb__dilemma"
  "ecp5_mini|joshajohnson__ecp5_mini"
  "neptune|wntrblm__neptune-mainboard"
  "sechzig|machdyne__sechzig_ml2"
  "core1106_cam|exie1122__core1106-stereo"
  "eit_mux|ErenErenel__eit_multiplexer"
  "nebula_watch|cactusman__nebula-watch"
  "pico_disp|homelith__pico-disp-ident"
  "usb_pd|loxodes__usb_pd"
)

for entry in "${MAP[@]}"; do
  IFS='|' read -r name frag <<< "$entry"
  srcfile=$(find "$SRC" -maxdepth 1 -name '*.kicad_pcb' -name "*${frag}*" | head -1)
  if [ -z "$srcfile" ]; then echo "MISS $name (frag '$frag')"; continue; fi
  echo "== $name <- $(basename "$srcfile")"
  "$KPY" "$PREP" "$srcfile" "$STRESS/boards_set5/$name.kicad_pcb" \
         "$STRESS/boards_unrouted_set5/$name.kicad_pcb" 2>/dev/null || echo "  FAIL $name"
  profile="${srcfile%.kicad_pcb}.kicad_pro"
  [ -f "$profile" ] && cp "$profile" "$STRESS/boards_set5/$name.kicad_pro"
done
echo "Done. stripped -> boards_unrouted_set5/ ; routed reference -> boards_set5/"
