#!/bin/bash
# Normalize+strip every set30 board (one pcbnew process each, segfault-safe).
# Reuses prep_set2.py (generic: <src> <routed_dst> <stripped_dst>).
#   stripped, unrouted boards -> boards_unrouted_set30/
#   normalized routed reference + .kicad_pro -> boards_set30/
# Auto-generated by assemble_corpus.py. Sources are modern KiCad (v6+).
set -u
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STRESS="${STRESS_DIR:-$HOME/Documents/kicad_stress_test}"
SRC="$STRESS/sources/github_set30"
KPY="${KICAD_PYTHON:-/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3}"
PREP="$SELF/prep_set2.py"
mkdir -p "$STRESS/boards_unrouted_set30" "$STRESS/boards_set30"

# short-name | source-filename-fragment (unique within github_set30/)
MAP=(
  "a13_test|a13_test"
  "a500_2meg_chip_ram|a500_2meg_chip_ram"
  "a591|a591"
  "amigaa500dram|amigaa500dram"
  "c64_250407|c64_250407"
  "cider|cider"
  "computie_68kboard|computie_68kboard"
  "gottagofazt3r|gottagofazt3r"
  "h616_lpddr4|h616_lpddr4"
  "icepi_sbc_h3|icepi_sbc_h3"
  "imx6ulz_4l|imx6ulz_4l"
  "macclassicramcard|macclassicramcard"
  "mackerel30_proto|mackerel30_proto"
  "maxi030|maxi030"
  "mcd_pcb|mcd_pcb"
  "n2630|n2630"
  "pcie_backplane_x16|pcie_backplane_x16"
  "pistormx_1k2|pistormx_1k2"
  "ram2e|ram2e"
  "sam9g25|sam9g25"
  "stm32h7s3_som|stm32h7s3_som"
  "zynq_ruler|zynq_ruler"
)

for entry in "${MAP[@]}"; do
  IFS='|' read -r name frag <<< "$entry"
  srcfile=$(find "$SRC" -maxdepth 1 -name '*.kicad_pcb' -name "*${frag}*" | head -1)
  if [ -z "$srcfile" ]; then echo "MISS $name (frag '$frag')"; continue; fi
  echo "== $name <- $(basename "$srcfile")"
  "$KPY" "$PREP" "$srcfile" "$STRESS/boards_set30/$name.kicad_pcb" \
         "$STRESS/boards_unrouted_set30/$name.kicad_pcb" 2>/dev/null || echo "  FAIL $name"
  profile="${srcfile%.kicad_pcb}.kicad_pro"
  [ -f "$profile" ] && cp "$profile" "$STRESS/boards_set30/$name.kicad_pro"
done
echo "Done. stripped -> boards_unrouted_set30/ ; routed reference -> boards_set30/"
