#!/bin/bash
# Normalize+strip every set29 board (one pcbnew process each, segfault-safe).
# Reuses prep_set2.py (generic: <src> <routed_dst> <stripped_dst>).
#   stripped, unrouted boards -> boards_unrouted_set29/
#   normalized routed reference + .kicad_pro -> boards_set29/
# Auto-generated by assemble_corpus.py. Sources are modern KiCad (v6+).
set -u
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STRESS="${STRESS_DIR:-$HOME/Documents/kicad_stress_test}"
SRC="$STRESS/sources/github_set29"
KPY="${KICAD_PYTHON:-/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3}"
PREP="$SELF/prep_set2.py"
mkdir -p "$STRESS/boards_unrouted_set29" "$STRESS/boards_set29"

# short-name | source-filename-fragment (unique within github_set29/)
MAP=(
  "am32_esc|am32_esc"
  "amulet_controller|amulet_controller"
  "bad_thing_kbd|bad_thing_kbd"
  "driverino|driverino"
  "edgeberry|edgeberry"
  "esp_rust_board|esp_rust_board"
  "piunora|piunora"
  "tfgps01|tfgps01"
  "tokay_lite|tokay_lite"
  "twonkie|twonkie"
  "uecg|uecg"
  "usbarmory|usbarmory"
)

for entry in "${MAP[@]}"; do
  IFS='|' read -r name frag <<< "$entry"
  srcfile=$(find "$SRC" -maxdepth 1 -name '*.kicad_pcb' -name "*${frag}*" | head -1)
  if [ -z "$srcfile" ]; then echo "MISS $name (frag '$frag')"; continue; fi
  echo "== $name <- $(basename "$srcfile")"
  "$KPY" "$PREP" "$srcfile" "$STRESS/boards_set29/$name.kicad_pcb" \
         "$STRESS/boards_unrouted_set29/$name.kicad_pcb" 2>/dev/null || echo "  FAIL $name"
  profile="${srcfile%.kicad_pcb}.kicad_pro"
  [ -f "$profile" ] && cp "$profile" "$STRESS/boards_set29/$name.kicad_pro"
done
echo "Done. stripped -> boards_unrouted_set29/ ; routed reference -> boards_set29/"
