#!/bin/bash
# Normalize+strip every set-4 board (one pcbnew process each, segfault-safe).
# Reuses prep_set2.py (generic: <src> <routed_dst> <stripped_dst>).
#   stripped, unrouted boards -> boards_unrouted_set4/
#   normalized routed reference + .kicad_pro -> boards_set4/
# Auto-generated by sources/assemble_corpus.py. Sources are modern KiCad (v6+).
set -u
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STRESS="${STRESS_DIR:-$HOME/Documents/kicad_stress_test}"
SRC="$STRESS/sources/github_set4"
KPY="${KICAD_PYTHON:-/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3}"
PREP="$SELF/prep_set2.py"
mkdir -p "$STRESS/boards_unrouted_set4" "$STRESS/boards_set4"

# short-name | source-filename-fragment (unique within github_set4/)
MAP=(
  "can_shield|greenlion__can_shield"
  "esp32s3_ref|binary12spy__esp32-s3-reference"
  "hid_remapper|jfedor2__hid-remapper"
  "rp2040_dev|Dee24r__rp2040Dev"
  "rp2350_dev|rubey4112__rp2350-devboard"
  "eurorack_pmod|apfaudio__eurorack-pmod-r35"
  "icepi_zero|cheyao__icepi_zero"
  "kuchen|machdyne__kuchen"
  "zynq_ad9364|kangyuzhe__zynq7020_ad9364"
  "macropad4l|Schmacksby__macropad"
  "openstint|zsellera__openstint_transponder"
  "picodvi|wren6991__picodvi"
  "usb_fm_radio|anttikes__usb_fm_radio"
  "vfo_ctrl|xflyingcat__vfo_controller"
)

for entry in "${MAP[@]}"; do
  IFS='|' read -r name frag <<< "$entry"
  srcfile=$(find "$SRC" -maxdepth 1 -name '*.kicad_pcb' -name "*${frag}*" | head -1)
  if [ -z "$srcfile" ]; then echo "MISS $name (frag '$frag')"; continue; fi
  echo "== $name <- $(basename "$srcfile")"
  "$KPY" "$PREP" "$srcfile" "$STRESS/boards_set4/$name.kicad_pcb" \
         "$STRESS/boards_unrouted_set4/$name.kicad_pcb" 2>/dev/null || echo "  FAIL $name"
  profile="${srcfile%.kicad_pcb}.kicad_pro"
  [ -f "$profile" ] && cp "$profile" "$STRESS/boards_set4/$name.kicad_pro"
done
echo "Done. stripped -> boards_unrouted_set4/ ; routed reference -> boards_set4/"
