"""What #799's feasibility check actually does, measured. NOT a test.

Named `measure_*` so `tests/run_all.py` never collects it (it discovers
`test_*.py` only): it sweeps thousands of constructed intents and takes minutes.
Its committed output is what `tests/test_799_feasibility_claims.py` asserts, so
no number in the PR body lives only in a terminal.

Three arms, and the first one is the honest caveat rather than the result.

ARM A -- INERTNESS. `floorplan.emit_intent` writes `'keepouts': []`
unconditionally (a keep-out is a mechanical fact no board can disclose) and no
CLI flag creates one, so EVERY intent this repo can generate is structurally
unreachable by this check. Comparing the full violation multiset before and
after therefore measures INERTNESS, not correctness. It is worth measuring --
it is what protects every downstream consumer -- but it is not evidence the
check is right, and the PR must say so in those words. Run it in the base tree
and the head tree with `--dump PATH` and diff the two files.

ARM B -- CONSTRUCTED INTENTS, generated BY RULE. Boards are filtered by
properties fixed before the run (a trustworthy outline, >= 20 footprints), the
probed members are the largest courtyards by area, and the zone/keep-out
geometry comes from a fixed ladder crossed with a coverage fraction. Nothing is
selected for its answer, and the boards the filter drops are named.

ARM C -- AGREEMENT against `seeder.count_legal_poses`, an INDEPENDENT answer to
"is there a pose" written for a different purpose. The comparison is
ASYMMETRIC, and stating it symmetrically would publish a number in the feature's
favour:

  * for a NON-ANCHOR zone, `pose_ok` is stronger than this check's question --
    it also demands board containment and neighbour clearance -- so a pose it
    finds is a pose that exists, and a refusal against `oracle >= 1` is a HARD
    FALSE POSITIVE. Target 0, pre-registered before the run.
    THE QUALIFIER IS LOAD-BEARING. In ANCHOR mode the two disagree by
    construction: `seeder.zone_gate` constrains the footprint ORIGIN and this
    check grades the courtyard CENTRE, and the branch documents that they can be
    disjoint -- so there a census hit is not evidence of a bug. And this sweep
    NEVER REACHES anchor mode: every zone here is the member's own courtyard
    bbox inflated by a margin >= 0, which always satisfies
    `zone_fits_courtyard`. So `hard_false_positives == 0` is evidence about the
    NON-ANCHOR branch only, and says nothing about the anchor one.
  * a census of 0 is NOT decisive. `zone_census_offsets` samples a lattice, and
    seeder.py records its own divergences ("4 of 65 movable parts census 0 while
    `_try_place` seats them"). So "check silent while oracle 0" is a SOFT
    suspected miss, reported as its own number and never folded into the
    headline.

Both anti-vacuity bounds are computed and printed, because a sweep with no hits
proves nothing and a sweep with no misses proves nothing either:

  H = cases where the check refuses and the pre-#799 total-coverage test did not
      (the widening did something on real geometry, not only on the hand-written
      counterexample)
  M = cases where the check is silent and a pose provably exists
      (it is not simply refusing everything with a keep-out in it)
"""
import argparse
import json
import math
import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, 'py_router'))
sys.path.insert(0, os.path.join(_ROOT, 'py_placer'))

from kicad_parser import parse_kicad_pcb            # noqa: E402
from placement import floorplan, legality, seeder   # noqa: E402
from placement.quench import QuenchState            # noqa: E402

#: Fixed before the run. A board qualifies on PROPERTIES, never by name.
MIN_FOOTPRINTS = 20
MEMBERS_PER_BOARD = 3
#: Zone = the member's own courtyard AABB inflated by this ladder.
MARGINS = (0.0, 0.25, 1.0, 4.0)
TOLERANCES = (0.0, 0.5, 2.0)
#: Fraction of the tolerance-inflated zone the keep-out family covers. 0.0 and
#: 1.0 are BOTH kept: a sweep that drops its own counterexamples proves nothing.
FRACTIONS = (0.0, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99, 1.0)
FAMILIES = ('edge', 'joint', 'circle')
FILTERS = ('plain', 'allow', 'sides')


def corpus_boards():
    """The boards git TRACKS, via the shared helper -- never a directory glob.

    Measured the hard way while writing this: `kicad_files/` accumulates
    GENERATED, gitignored boards, so a plain glob returned 22 entries in a
    fresh worktree and 28 in one that had just run the suite. The two arms then
    compared different corpora and the diff was six phantom boards.
    `run_utils.corpus_boards` exists for exactly this and says so.
    """
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import run_utils
    boards = run_utils.corpus_boards()
    if not boards:
        raise SystemExit("SKIP: git cannot list kicad_files/, so the corpus "
                         "this claims to sweep cannot be identified")
    return [b if os.path.isabs(b) else os.path.join(_ROOT, b)
            for b in boards]


def arm_offcentre():
    """How many corpus parts have an OFF-CENTRE courtyard, and by how much.

    This is the number the anchor design turns on: `zone_escape(anchor=True)`
    grades the courtyard CENTRE while `seeder.zone_gate` constrains the
    footprint ORIGIN, and they differ by exactly this offset. An earlier draft
    of the check intersected the two conventions, which is empty wherever the
    offset exceeds the zone extent.

    It lives here because it was first quoted from a one-off probe and the
    figure was WRONG -- 419 of 1507, from a directory glob over generated
    boards. Re-derived over the git-tracked corpus it is 234 of 1316. A
    measured number needs a committed measurement.
    """
    tot = off = 0
    worst = (0.0, '', '')
    for p in corpus_boards():
        pcb = parse_kicad_pcb(p)
        for ref, lb in legality.part_local_bounds(pcb, p).items():
            if lb.synthetic:
                continue
            tot += 1
            cx = (lb.local[0] + lb.local[2]) / 2.0
            cy = (lb.local[1] + lb.local[3]) / 2.0
            d = max(abs(cx), abs(cy))
            if d > 1e-9:
                off += 1
            if d > worst[0]:
                worst = (d, os.path.basename(p), ref)
    print(f"OFF-CENTRE COURTYARDS: {off} of {tot} non-synthetic parts over "
          f"{len(corpus_boards())} git-tracked boards "
          f"({100.0 * off / max(1, tot):.0f}%)")
    print(f"  worst offset {worst[0]:.3f} mm -- {worst[1]} {worst[2]}")
    return {'parts': tot, 'off_centre': off,
            'worst_offset_mm': round(worst[0], 3),
            'worst_board': worst[1], 'worst_ref': worst[2]}


def _ko(name, rect=None, circle=None, allow=(), sides=('F', 'B')):
    e = {'name': name, 'allow': tuple(allow), 'sides': tuple(sides)}
    if rect is not None:
        e['rect'] = tuple(float(v) for v in rect)
    else:
        e['circle'] = tuple(float(v) for v in circle)
    return e


def keepouts_for(family, reach, frac, ref, filt):
    """The keep-out family at coverage `frac` of `reach`, by rule."""
    x0, y0, x1, y1 = reach
    w, h = x1 - x0, y1 - y0
    allow = (ref,) if filt == 'allow' else ()
    sides = ('B',) if filt == 'sides' else ('F', 'B')
    if frac <= 0.0:
        return []
    if family == 'edge':
        return [_ko('edge', rect=(x0, y0, x0 + w * frac, y1),
                    allow=allow, sides=sides)]
    if family == 'joint':
        # Each covers a bit over half of `frac`, from opposite edges, so
        # neither is fatal alone until frac is large.
        half = frac / 2.0 + 1e-9
        return [_ko('west', rect=(x0, y0, x0 + w * half, y1),
                    allow=allow, sides=sides),
                _ko('east', rect=(x1 - w * half, y0, x1, y1),
                    allow=allow, sides=sides)]
    # a disc of the radius covering `frac` of the reach AREA, centred
    r = math.sqrt(max(0.0, frac) * w * h / math.pi)
    return [_ko('disc', circle=((x0 + x1) / 2.0, (y0 + y1) / 2.0, r),
                allow=allow, sides=sides)]


def arm_a(dump):
    """Inertness: the full violation multiset of every emitted intent."""
    out = {}
    for p in corpus_boards():
        name = os.path.basename(p)
        try:
            pcb = parse_kicad_pcb(p)
            doc = floorplan.emit_intent(pcb, p)
            intent = floorplan.intent_from_dict(doc)
            g = floorplan.grade(intent, pcb, p)
            _b, probs = floorplan.resolve_intent_gate(intent, pcb, ())
            out[name] = {
                'keepouts_declared': len(doc.get('keepouts') or []),
                'allow_patterns': sum(len(k.get('allow') or ())
                                      for k in (doc.get('keepouts') or [])),
                'grade': sorted(f"{v.rule}|{v.ref or ''}|{v.block or ''}|"
                                f"{v.severity}|{v.message}"
                                for v in g.violations),
                'gate': sorted(f"{v.rule}|{v.ref or ''}|{v.block or ''}|"
                               f"{v.severity}|{v.message}" for v in probs),
            }
        except Exception as e:                       # noqa: BLE001
            out[name] = {'error': f"{type(e).__name__}: {e}"}
    with open(dump, 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=1, sort_keys=True)
    # POSITIVE CONTROL on the comparator, so "identical on all N" is not
    # trivially satisfied by a comparison that compares nothing. This used to
    # be claimed in prose and run by hand; now it runs here and prints.
    probe = json.loads(json.dumps(out))
    first = sorted(k for k, v in probe.items() if 'error' not in v)
    if first:
        probe[first[0]]['grade'] = list(probe[first[0]]['grade']) + [
            'injected|X||error|control record']
        detected = [k for k in out if out.get(k) != probe.get(k)]
        print(f"  comparator positive control: injected 1 record into "
              f"{first[0]} -> {len(detected)} board(s) reported differing "
              f"{'(OK)' if detected == [first[0]] else '(BLIND -- the '
               'comparison proves nothing)'}")
    ok = [v for v in out.values() if 'error' not in v]
    print(f"ARM A: {len(out)} board(s), {len(ok)} graded, "
          f"{sum(v['keepouts_declared'] for v in ok)} keep-out(s) declared "
          f"across all of them, {sum(v['allow_patterns'] for v in ok)} "
          f"allow pattern(s)")
    print(f"  wrote {dump} -- diff it against the base tree's copy")


def probe_members(pcb, path):
    """The largest-courtyard members, by rule -- plus the largest SMD-ONLY one.

    The SMD slot is not decoration. Ranking by courtyard area alone picks
    connectors, and every connector on these boards has through pads, so it
    occupies BOTH faces and a `sides: ["B"]` keep-out legitimately binds it.
    Measured on a 2-board pilot: all 758 refusals under the `sides` exemption
    were through-hole parts, and the sweep contained no part for which that
    exemption could ever fire. An arm with no eligible subject is a vacuous
    arm that reads as a passing one.
    """
    lb = legality.part_local_bounds(pcb, path)
    def area(v):
        return ((v.local[2] - v.local[0]) * (v.local[3] - v.local[1]))
    ranked = sorted(((r, v) for r, v in lb.items() if not v.synthetic),
                    key=lambda kv: (-area(kv[1]), kv[0]))
    out = ranked[:MEMBERS_PER_BOARD]
    smd = [(r, v) for r, v in ranked if not v.has_tht]
    if smd and not any(not v.has_tht for _r, v in out):
        out = out[:-1] + smd[:1] if len(out) >= MEMBERS_PER_BOARD else out + smd[:1]
    return out


def arm_bc(limit_boards, verbose):
    rows = []
    dropped = []
    boards = corpus_boards()
    for p in boards:
        name = os.path.basename(p)
        try:
            pcb = parse_kicad_pcb(p)
        except Exception as e:                       # noqa: BLE001
            dropped.append((name, f"parse: {type(e).__name__}"))
            continue
        if len(pcb.footprints or {}) < MIN_FOOTPRINTS:
            dropped.append((name, f"{len(pcb.footprints or {})} footprints "
                                  f"< {MIN_FOOTPRINTS}"))
            continue
        try:
            if not floorplan.outline_state(pcb, p)['trustworthy']:
                dropped.append((name, "outline not trustworthy"))
                continue
        except Exception as e:                       # noqa: BLE001
            dropped.append((name, f"outline: {type(e).__name__}"))
            continue
        members = probe_members(pcb, p)
        if not members:
            dropped.append((name, "no non-synthetic member"))
            continue
        try:
            state = QuenchState(pcb, p, 0.25, 0.55, 10.0, 0.5, 0.25,
                                2.0, 2.0, 2.0, 0.1, 1.0)
        except Exception as e:                       # noqa: BLE001
            dropped.append((name, f"state: {type(e).__name__}"))
            continue
        others = set(state.parts) - {r for r, _ in members}

        for ref, lb in members:
            fp = pcb.footprints[ref]
            part = floorplan._LocalPart(fp.rotation or 0.0,
                                        lb.local, lb.tht_local)
            b = part.rect(fp.x, fp.y, fp.rotation or 0.0)
            for margin in MARGINS:
                zone = (b[0] - margin, b[1] - margin,
                        b[2] + margin, b[3] + margin)
                for tol in TOLERANCES:
                    reach = (zone[0] - tol, zone[1] - tol,
                             zone[2] + tol, zone[3] + tol)
                    for fam in FAMILIES:
                        for frac in FRACTIONS:
                            for filt in FILTERS:
                                kos = keepouts_for(fam, reach, frac, ref, filt)
                                sides = legality.sides_occupied(
                                    legality.footprint_side(fp),
                                    legality.footprint_has_through_pads(fp))
                                bound = floorplan.keepouts_for_ref(
                                    kos, ref, sides)
                                v = floorplan.zone_pose_feasibility(
                                    zone, tol, part, bound)
                                # The pre-#799 answer, for H.
                                zobj = type('Z', (), {'rect': zone})()
                                old = floorplan.zone_covered_by_keepout(
                                    zobj, kos, {ref: sides}, tol)
                                rows.append({
                                    'board': name, 'ref': ref,
                                    'margin': margin, 'tol': tol,
                                    'family': fam, 'frac': frac,
                                    'filter': filt,
                                    'bound': len(bound),
                                    'has_tht': bool(lb.has_tht),
                                    'feasible': bool(v['feasible']),
                                    'reason': v['reason'],
                                    'old_total_coverage': old is not None,
                                    'zone': [round(c, 4) for c in zone],
                                })
                                # ORACLE, only where it can decide something:
                                # the census is expensive, so ask it on every
                                # REFUSAL (where a hit is a hard bug) and on a
                                # deterministic slice of the rest.
                                ask = (not v['feasible']) or (
                                    frac in (0.5, 0.99) and filt == 'plain')
                                if not ask:
                                    continue
                                # ONE state per board, with `keepouts_for`
                                # swapped per case -- the same mutate-and-
                                # restore `count_legal_poses`' own keep-out
                                # LIFT does. Rebuilding a QuenchState per case
                                # costs 0.15s on a 65-part board and 0.75s on a
                                # 266-part one, which made this arm hours long
                                # for a value it recomputes identically.
                                saved = state.keepouts_for.get(ref)
                                try:
                                    if bound:
                                        state.keepouts_for[ref] = tuple(bound)
                                    elif ref in state.keepouts_for:
                                        del state.keepouts_for[ref]
                                    state._inc_intent.clear()
                                    n = seeder.count_legal_poses(
                                        state, ref, fp.x, fp.y, others,
                                        constraint=tuple(zone), tol=tol,
                                        cap=1)
                                except Exception as e:   # noqa: BLE001
                                    rows[-1]['oracle'] = f"ERR:{type(e).__name__}"
                                    continue
                                finally:
                                    if saved is not None:
                                        state.keepouts_for[ref] = saved
                                    elif ref in state.keepouts_for:
                                        del state.keepouts_for[ref]
                                    state._inc_intent.clear()
                                rows[-1]['oracle'] = int(n)
        if limit_boards and len({r['board'] for r in rows}) >= limit_boards:
            break

    return rows, dropped


def report(rows, dropped):
    n = len(rows)
    refused = [r for r in rows if not r['feasible']]
    old_hit = [r for r in rows if r['old_total_coverage']]
    H = [r for r in refused if not r['old_total_coverage']]
    with_oracle = [r for r in rows if isinstance(r.get('oracle'), int)]
    hard_fp = [r for r in with_oracle if not r['feasible'] and r['oracle'] >= 1]
    M = [r for r in with_oracle if r['feasible'] and r['oracle'] >= 1]
    soft = [r for r in with_oracle if r['feasible'] and r['oracle'] == 0]

    print(f"\nARM B/C: {n} case(s) over "
          f"{len({r['board'] for r in rows})} board(s), "
          f"{len({(r['board'], r['ref']) for r in rows})} member(s)")
    if dropped:
        print("  boards dropped by the property filter (named, not hidden):")
        for name, why in dropped:
            print(f"    - {name}: {why}")
    print(f"  refused by the widened check ........ {len(refused)}")
    print(f"  refused by the OLD total-coverage test {len(old_hit)}")
    print(f"  H  refused now, not before .......... {len(H)}   "
          f"{'OK' if H else 'VACUOUS -- the sweep proves nothing'}")
    print(f"  oracle consulted .................... {len(with_oracle)}")
    print(f"  M  silent AND a pose provably exists  {len(M)}   "
          f"{'OK' if M else 'VACUOUS -- the check may refuse everything'}")
    print(f"  HARD FALSE POSITIVES (refused, pose exists) "
          f"{len(hard_fp)}   {'OK' if not hard_fp else 'BUG'}")
    print(f"  soft suspected misses (silent, census 0) {len(soft)}"
          f"   -- NOT decisive; the census is a lattice")
    for r in hard_fp[:10]:
        print(f"    HARD FP: {r['board']} {r['ref']} {r['family']} "
              f"frac={r['frac']} tol={r['tol']} margin={r['margin']} "
              f"reason={r['reason']} zone={r['zone']}")

    print("\n  flip point per family (lowest frac that refuses, plain filter):")
    for fam in FAMILIES:
        fr = sorted({r['frac'] for r in refused
                     if r['family'] == fam and r['filter'] == 'plain'})
        print(f"    {fam:<7} {fr[0] if fr else 'never refuses'}"
              + ("   <-- refusing at frac 0 would contradict arm O"
                 if fr and fr[0] == 0.0 else ""))
    # THE INVARIANT IS THE RESOLVER'S OWN ANSWER, not a proxy for it. Two
    # earlier versions of this block used proxies and both were wrong:
    # "no refusal under `sides`" (wrong -- a through-hole part occupies BOTH
    # faces, so a B-side keep-out binds an F-side THT part on purpose), then
    # "every `sides` refusal is a through-hole part" (wrong too -- measured
    # 624 refusals of B-SIDE SMD parts, which a B-side keep-out also binds,
    # correctly). The question either proxy was groping for is simply whether
    # `keepouts_for_ref` bound anything, and `bound` records exactly that.
    unbound = [r for r in refused if not r['bound']]
    print(f"  refusals with NO binding keep-out: {len(unbound)}   "
          f"{'OK -- every refusal names a keep-out that binds it' if not unbound else 'BUG'}")
    # `bound == 0` has TWO causes and only one of them is an exemption: at
    # `frac == 0` no keep-out is declared at all. Counting them together
    # inflated the exemption evidence by 1404 rows per filter.
    for filt in ('allow', 'sides'):
        f_rows = [r for r in rows if r['filter'] == filt]
        declared = [r for r in f_rows if r['frac'] > 0.0]
        exempt = [r for r in declared if not r['bound']]
        ref_ex = [r for r in exempt if not r['feasible']]
        print(f"  `{filt}`: of {len(declared)} case(s) that DECLARE a keep-out, "
              f"{len(exempt)} were exempted by the resolver and {len(ref_ex)} "
              f"of those refused   {'OK' if not ref_ex else 'BUG'}"
              + ('' if exempt else
                 "   VACUOUS -- the exemption was never exercised"))
    return {'cases': n, 'refused': len(refused), 'old_total_coverage':
            len(old_hit), 'H': len(H), 'M': len(M),
            'refusals_with_no_binding_keepout': len(unbound),
            'exempted_cases': sum(1 for r in rows
                                  if r['frac'] > 0.0 and not r['bound']),
            'no_keepout_declared_cases': sum(1 for r in rows
                                             if r['frac'] <= 0.0),
            'oracle_consulted': len(with_oracle),
            'hard_false_positives': len(hard_fp), 'soft_misses': len(soft),
            'boards': sorted({r['board'] for r in rows}),
            'dropped': [list(d) for d in dropped]}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--dump', metavar='PATH',
                    help='ARM A only: write the inertness record and exit')
    ap.add_argument('--rows', metavar='PATH', help='write the raw rows')
    ap.add_argument('--summary', metavar='PATH',
                    help='write the summary the claims test reads')
    ap.add_argument('--boards', type=int, default=0,
                    help='stop after N boards (a declared cap, not a filter)')
    ap.add_argument('--from-rows', metavar='PATH',
                    help='re-derive the summary from committed rows, running '
                         'nothing -- the change detector for the published '
                         'numbers')
    ap.add_argument('--offcentre', action='store_true',
                    help='ARM: the off-centre courtyard census the anchor '
                         'design turns on')
    ap.add_argument('-v', '--verbose', action='store_true')
    a = ap.parse_args()
    if a.offcentre:
        d = arm_offcentre()
        if a.summary:
            with open(a.summary, 'w', encoding='utf-8') as f:
                json.dump(d, f, indent=1, sort_keys=True)
        return 0
    if a.from_rows:
        with open(a.from_rows, encoding='utf-8') as f:
            rows = [json.loads(line) for line in f if line.strip()]
        summ = report(rows, [])
        if a.summary:
            with open(a.summary, 'w', encoding='utf-8') as f:
                json.dump(summ, f, indent=1, sort_keys=True)
        return 1 if summ['hard_false_positives'] else 0
    if a.dump:
        arm_a(a.dump)
        return 0
    rows, dropped = arm_bc(a.boards, a.verbose)
    summ = report(rows, dropped)
    if a.boards:
        summ['declared_cap'] = a.boards
        print(f"\n  NOTE: capped at {a.boards} board(s) by --boards. The cap is "
              f"recorded in the summary, never applied silently.")
    if a.rows:
        with open(a.rows, 'w', encoding='utf-8') as f:
            for r in rows:
                f.write(json.dumps(r, sort_keys=True) + '\n')
        print(f"  rows -> {a.rows}")
    if a.summary:
        with open(a.summary, 'w', encoding='utf-8') as f:
            json.dump(summ, f, indent=1, sort_keys=True)
        print(f"  summary -> {a.summary}")
    return 1 if summ['hard_false_positives'] else 0


if __name__ == '__main__':
    sys.exit(main())
