#!/usr/bin/env python3
"""#841: the ONE rectangle a lane ledger charges a neighbour.

`escape` charged the bbox of pad CENTRES; `routability.face_lane_ledger`
charged the COURTYARD. The kernel they share since #835 takes its rects from
the caller, so the two answered the same question differently -- by 2 to 7x on
five boards.

This file pins the rect ITSELF, before either consumer uses it, so a later
change to a ledger cannot quietly redefine what "obstruction" means.

What is asserted, and why each one is here rather than implied:

  1. It is the pad-COPPER box, and it is `PartPads.extent` -- CALLED, not
     re-derived. A second copy of that geometry is how the two channels came
     to disagree in the first place.
  2. It is strictly WIDER than the pad-centre box wherever a part has more
     than one pad. The old rect is the degenerate case, not a conservative
     one: a two-terminal passive contributes a zero-width obstruction.
  3. It is NOT the courtyard, on a board where the two differ. Without this,
     a well-meaning edit could satisfy every other assertion here by handing
     back `GradedPart.rect`.
  4. A footprint with no pads is ABSENT, not present with a fiction. This is
     the `synthetic` hazard #841 names, closed by construction.
  5. `clearance` reaches the result. It is easy to read this parameter as
     decoration -- `extent` is a copper box -- but NPTH growth is folded into
     it, so a hardcoded clearance would price a mounting hole wrongly and
     nothing else in the file would notice.
  6. `copper` is inside `rect`, and every EDGE of `copper` is attained by some
     pad. That is not decoration either: it is the property that keeps an edge
     pad at distance exactly 0 once face assignment measures pad edges, which
     is what makes the subject-rect half of #841 invariant rather than
     catastrophic. `rect` does not have it -- 12 edges on the corpus are set
     by a mounting hole no pad reaches.
  7. A footprint whose pad model cannot be built degrades to the pad-CENTRE
     box and says so via `modelled`. A silent fallback makes a map of the
     wrong geometry look exactly like a map of the right one.

Run: python3 -X utf8 tests/test_841_obstruction_rect.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
for _p in (ROOT, os.path.join(ROOT, 'py_router'), os.path.join(ROOT, 'py_placer'),
           os.path.join(ROOT, 'py_tools'), os.path.join(ROOT, 'tests')):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import run_utils                                              # noqa: E402
from kicad_parser import parse_kicad_pcb                      # noqa: E402
from placement import escape as E                             # noqa: E402
from placement.legality import (_pad_carries_copper,          # noqa: E402
                                build_part_pads,
                                graded_parts_from_file,
                                pad_box,
                                pad_half_extents,
                                part_copper_geometry)

RUN_ALL_FAST_OK = True

#: Parts whose pad-copper extent MOVES with the clearance argument, and by how
#: much. All NPTH mounting holes: `PartPads` folds the growth
#: `max(0, npth_floor - clearance)` into `holes_extent`. Regenerated by THIS
#: file -- no `--table` prints per-part clearance data, and pointing at one
#: that does not is how a number stops being checkable.
NPTH_MOVERS = {
    'tigard': {'H1', 'H2', 'H3', 'H4'},
    'rp2350_fpga_eensy_prePlane': {'J2'},
}
NPTH_DELTA_MM = 0.200


def _board(name):
    for p in run_utils.corpus_boards():
        if os.path.splitext(os.path.basename(p))[0] == name:
            return parse_kicad_pcb(p), p
    return None, None


def test_it_is_PartPads_extent_called_not_copied():
    """Rule 1. The grader is CALLED; this test would pass on a copy that
    happened to agree today and drift tomorrow, so it compares object for
    object over every part of three boards rather than sampling."""
    if not run_utils.corpus_boards():
        print('SKIP: git could not name the tracked corpus')
        return
    seen = 0
    for name in ('tigard', 'glasgow_revC', 'rp2350_fpga_eensy_prePlane'):
        pcb, path = _board(name)
        if pcb is None:
            print('  SKIP {} absent'.format(name))
            continue
        geom = E.board_copper_geometry(pcb, 0.2)
        rects = {r: g.rect for r, g in geom.items()}
        parts = build_part_pads(pcb.footprints, 0.2)
        for ref, pp in parts.items():
            fp = pcb.footprints[ref]
            want = pp.extent(fp.x, fp.y, fp.rotation or 0.0)
            if want is None:
                assert ref not in rects, (
                    '{}: {} has no extent but is in the map'.format(name, ref))
                continue
            assert rects.get(ref) == want, (
                '{}: {} obstruction rect {} != PartPads.extent {}'
                .format(name, ref, rects.get(ref), want))
            seen += 1
    assert seen > 300, 'only {} parts compared; the corpus did not load'.format(seen)
    print('  PASS: {} parts, rect is PartPads.extent exactly'.format(seen))


def test_it_is_wider_than_the_pad_centre_box():
    """Rule 2. The old rect spans pad CENTRES, so it is contained in this one
    on every part, and STRICTLY smaller wherever a pad has area -- which is
    every real part. A part measured at its centres is not conservative; it is
    a part whose terminals do not exist."""
    if not run_utils.corpus_boards():
        print('SKIP: git could not name the tracked corpus')
        return
    strict = 0
    total = 0
    for name in ('tigard', 'glasgow_revC', 'watchy'):
        pcb, _p = _board(name)
        if pcb is None:
            print('  SKIP {} absent'.format(name))
            continue
        geom = E.board_copper_geometry(pcb, 0.2)
        rects = {r: g.rect for r, g in geom.items()}
        for ref, rect in rects.items():
            fp = pcb.footprints[ref]
            if not fp.pads:
                continue
            c = E._part_rect(fp)
            total += 1
            assert (rect[0] <= c[0] + 1e-9 and rect[1] <= c[1] + 1e-9
                    and rect[2] >= c[2] - 1e-9 and rect[3] >= c[3] - 1e-9), (
                '{}: {} copper rect {} does not contain the centre rect {}'
                .format(name, ref, rect, c))
            if (rect[2] - rect[0]) > (c[2] - c[0]) + 1e-6:
                strict += 1
    assert total > 200, 'only {} parts examined'.format(total)
    assert strict > 0.9 * total, (
        'only {} of {} parts are STRICTLY wider than their pad-centre box; '
        'the rect has collapsed back to centres'.format(strict, total))
    print('  PASS: {} of {} parts strictly wider than the pad-centre box'
          .format(strict, total))


def test_it_is_not_the_courtyard():
    """Rule 3. The change detector for the other wrong answer. Asserting only
    "wider than centres" would be satisfied by the courtyard too."""
    pcb, path = _board('glasgow_revC')
    if pcb is None:
        print('  SKIP glasgow_revC absent')
        return
    geom = E.board_copper_geometry(pcb, 0.2)
    rects = {r: g.rect for r, g in geom.items()}
    court = {g.ref: g.rect for g in graded_parts_from_file(pcb, path)}
    differ = sum(1 for r, v in rects.items()
                 if r in court and max(abs(a - b) for a, b in zip(v, court[r])) > 1e-6)
    assert differ > 0.5 * len(rects), (
        'only {} of {} rects differ from the courtyard; the map is charging '
        'assembly keep-out, not copper'.format(differ, len(rects)))
    print('  PASS: {} of {} rects differ from the courtyard'
          .format(differ, len(rects)))


def test_copper_is_inside_rect_and_every_copper_edge_is_attained_by_a_pad():
    """Rule 6, and the load-bearing one for face ASSIGNMENT.

    `CopperGeometry` carries two boxes because they answer different
    questions. `rect` is the obstruction box -- pad copper UNION the NPTH hole
    extents. `copper` is the pads alone, and face assignment is measured
    against it precisely because every one of its four edges is attained by
    some pad: that is what keeps an edge pad at distance exactly 0 once
    `_face_of` measures pad EDGES, which is what makes the subject-rect change
    invariant instead of catastrophic.

    The edge property holds BY CONSTRUCTION today -- `copper` is the min/max
    over the very pad rects it is checked against -- and the arm is here so
    that a future redefinition (building `copper` from `extent`, say) trips
    instead of quietly removing the guarantee `_face_of` rests on.

    The second half is not tautological and is the number that matters:
    `rect` does NOT have the property, and the test says how often rather than
    leaving it as an argument -- on the corpus's fine-pitch parts some edges
    are set by a mounting hole no pad reaches.
    """
    if not run_utils.corpus_boards():
        print('SKIP: git could not name the tracked corpus')
        return
    hole_set = 0
    faces = 0
    checked = 0
    for path in run_utils.corpus_boards():
        try:
            pcb = parse_kicad_pcb(path)
        except Exception:                                     # noqa: BLE001
            continue
        geom = E.board_copper_geometry(pcb, 0.2)
        refs = E.fine_pitch_parts(pcb)
        if not refs:
            continue
        checked += 1
        for ref in refs:
            g = geom.get(ref)
            if g is None or not g.modelled:
                continue
            r, c = g.rect, g.copper
            assert (r[0] <= c[0] + 1e-9 and r[1] <= c[1] + 1e-9
                    and r[2] >= c[2] - 1e-9 and r[3] >= c[3] - 1e-9), (
                '{}: {} copper {} is not inside rect {}'
                .format(os.path.basename(path), ref, c, r))
            for i, edge in enumerate(c):
                faces += 1
                hit = any(abs(b[i] - edge) < 1e-6 for b in g.pads.values())
                assert hit, (
                    '{}: {} copper edge {} ({}) is attained by no pad; face '
                    'assignment would have no zero-distance pad on that side'
                    .format(os.path.basename(path), ref, i, edge))
                if abs(r[i] - edge) > 1e-6:
                    hole_set += 1
    assert checked >= 5, 'only {} board(s) had a fine-pitch part'.format(checked)
    assert faces > 200, 'only {} edges examined'.format(faces)
    assert hole_set > 0, (
        'no face has its extent edge set by a hole rather than by copper, so '
        'the two boxes are interchangeable here and this arm proves nothing -- '
        'which would mean `copper` can be dropped')
    print('  PASS: copper inside rect on {} edges over {} board(s); {} edges '
          'are set by a hole, not by a pad'.format(faces, checked, hole_set))


def test_copper_is_the_union_of_the_pad_rects_and_each_pad_finds_its_own():
    """Rule 8, and the arm whose ABSENCE let a real bug ship for six commits.

    The edge arm above holds BY CONSTRUCTION, so it cannot see `copper` being
    built from a lossy source -- and it was. `pads` was keyed on the pad's
    CENTRE alone, so pads STACKED at one point collapsed to whichever came
    last, and `copper` (built from that dict) silently lost them: ulx3s U1
    dropped 4 of its 389 rects and came out 0.1905mm short on two sides, and
    glasgow_revC U1's 0.6mm GND pad 57 was handed a co-located 6.22mm box.
    Every arm in this file passed throughout.

    So this one compares against `PartPads.pad_rects` directly -- the thing
    `copper` claims to be the union of -- and checks that each pad's lookup
    returns a box centred on THAT pad. A lookup that quietly hands back a
    neighbour's rectangle is worse than one that misses, and only the second
    assertion can tell them apart.
    """
    if not run_utils.corpus_boards():
        print('SKIP: git could not name the tracked corpus')
        return
    parts = pads = stacked = 0
    for path in run_utils.corpus_boards():
        try:
            pcb = parse_kicad_pcb(path)
        except Exception:                                     # noqa: BLE001
            continue
        fps = pcb.footprints
        pp = build_part_pads(fps, 0.2, tolerant=True)
        geom = part_copper_geometry(fps, 0.2, parts=pp)
        for ref, g in geom.items():
            if not g.modelled:
                continue
            fp = fps[ref]
            boxes = [(r[0], r[1], r[2], r[3])
                     for r in pp[ref].pad_rects(fp.x, fp.y, fp.rotation or 0.0)]
            if not boxes:
                continue
            parts += 1
            want = (min(b[0] for b in boxes), min(b[1] for b in boxes),
                    max(b[2] for b in boxes), max(b[3] for b in boxes))
            assert max(abs(a - b) for a, b in zip(want, g.copper)) < 1e-9, (
                '{}: {} copper {} is not the union of its {} pad rects {}'
                .format(os.path.basename(path), ref, g.copper, len(boxes),
                        want))
            if len(g.pads) < len(boxes):
                stacked += 1
            for pad in fp.pads:
                box = pad_box(g, pad)
                if box is None:
                    assert not _pad_carries_copper(pad), (
                        '{}: {} pad {} carries copper and has no rect'
                        .format(os.path.basename(path), ref, pad.pad_number))
                    continue
                pads += 1
                cx = (box[0] + box[2]) / 2.0
                cy = (box[1] + box[3]) / 2.0
                assert (abs(cx - pad.global_x) < 1e-6
                        and abs(cy - pad.global_y) < 1e-6), (
                    "{}: {} pad {} was handed a box centred at ({}, {}), not "
                    "its own ({}, {})".format(
                        os.path.basename(path), ref, pad.pad_number, cx, cy,
                        pad.global_x, pad.global_y))
                # ...and its SIZE, which is the half the centre cannot see:
                # pads stacked at one point share a centre BY DEFINITION, so
                # a centre-only check passes on every wrong hit among exactly
                # the pads this lookup was rekeyed for. The mutation battery
                # caught that -- `the-pad-lookup-key-drops-the-size` survived
                # the first version of this arm.
                whx, why = pad_half_extents(pad)
                assert (abs((box[2] - box[0]) / 2.0 - whx) < 1e-6
                        and abs((box[3] - box[1]) / 2.0 - why) < 1e-6), (
                    "{}: {} pad {} is {:.4f}x{:.4f} but was handed a "
                    "{:.4f}x{:.4f} box -- a co-located pad's".format(
                        os.path.basename(path), ref, pad.pad_number,
                        whx * 2, why * 2,
                        box[2] - box[0], box[3] - box[1]))
    assert parts > 500, 'only {} parts examined'.format(parts)
    assert pads > 5000, 'only {} pads examined'.format(pads)
    print('  PASS: {} parts, copper is the pad-rect union; {} pads each found '
          'their own box ({} parts carry stacked pads)'
          .format(parts, pads, stacked))


def test_an_unmodellable_footprint_degrades_to_the_pad_centre_box():
    """Rule 7. The fallback is a live path, not a defensive gesture: the
    hand-built fixtures in `tests/test_escape_ledger.py` carry no `reference`,
    so `PartPads` raises on them and those tests' recorded numbers are
    pad-CENTRE numbers. `modelled` is what tells a reader which parts got
    which answer -- a silent fallback is how a map of the wrong geometry looks
    exactly like a map of the right one."""
    class _Pad:
        def __init__(self, x, y):
            self.global_x, self.global_y = x, y
            self.local_x, self.local_y = x, y
            self.net_id, self.drill = 1, 0.0
            self.size_x = self.size_y = 0.3
            self.layers, self.pad_type = ['F.Cu'], 'smd'
            self.rect_rotation = 0.0

    class _Fp:                       # deliberately missing `reference`
        def __init__(self, pads):
            self.pads = pads
            self.x, self.y, self.rotation = 0.0, 0.0, 0.0
            self.layer = 'F.Cu'
            self.footprint_name = 'QFN-32'

    fp = _Fp([_Pad(0.0, 0.0), _Pad(1.0, 2.0)])
    geom = part_copper_geometry({'U1': fp}, 0.2)
    g = geom['U1']
    assert g.modelled is False, 'the broken fixture was modelled after all'
    assert g.rect == g.copper == (0.0, 0.0, 1.0, 2.0), g
    assert g.pads == {}, g.pads
    assert g.rect == E._part_rect(fp), (
        'the fallback is not the pad-centre box the old ledger used')
    print('  PASS: an unmodellable footprint degrades to {} with '
          'modelled=False'.format(g.rect))


def test_a_padless_footprint_is_absent():
    """Rule 4. `legality.part_local_bounds` invents a +/-0.5mm box for a
    footprint with no courtyard AND no pads, and flags it `synthetic`.
    `grade_body_overlap` refuses to gate on those. A lane SUPPLY is a number
    `options.move_blocker` turns into "move this part", so the fiction must
    not reach it -- here it cannot, because no pads means no entry."""
    if not run_utils.corpus_boards():
        print('SKIP: git could not name the tracked corpus')
        return
    checked = 0
    for name in ('tigard', 'glasgow_revC'):
        pcb, _p = _board(name)
        if pcb is None:
            print('  SKIP {} absent'.format(name))
            continue
        geom = E.board_copper_geometry(pcb, 0.2)
        rects = {r: g.rect for r, g in geom.items()}
        padless = [r for r, f in pcb.footprints.items() if not (f.pads or [])]
        assert padless, '{}: no pad-less footprint to test with'.format(name)
        for r in padless:
            assert r not in rects, (
                '{}: pad-less {} is charged an obstruction'.format(name, r))
        checked += len(padless)
    assert checked >= 3, 'only {} pad-less footprints seen'.format(checked)
    print('  PASS: {} pad-less footprints, none charged'.format(checked))


def test_clearance_reaches_the_result_and_only_via_drilled_holes():
    """Rule 5. Two halves, and the second is the one that makes it a test
    rather than a demonstration: the clearance must move the NPTH parts AND
    must move nothing else. A blanket inflation would satisfy the first half
    alone."""
    if not run_utils.corpus_boards():
        print('SKIP: git could not name the tracked corpus')
        return
    for name, expect in sorted(NPTH_MOVERS.items()):
        pcb, _p = _board(name)
        if pcb is None:
            print('  SKIP {} absent'.format(name))
            continue
        tight = {r: g.rect for r, g in E.board_copper_geometry(pcb, 0.0).items()}
        loose = {r: g.rect for r, g in E.board_copper_geometry(pcb, 0.5).items()}
        moved = {r for r in tight
                 if max(abs(a - b) for a, b in zip(tight[r], loose[r])) > 1e-6}
        assert moved == expect, (
            '{}: parts moving with clearance {} != expected {}'
            .format(name, sorted(moved), sorted(expect)))
        for r in moved:
            d = max(abs(a - b) for a, b in zip(tight[r], loose[r]))
            assert abs(d - NPTH_DELTA_MM) < 1e-6, (
                '{}: {} moved {:.4f}mm, not the recorded {}mm'
                .format(name, r, d, NPTH_DELTA_MM))
        print('  PASS: {} -- {} moved by {}mm, nothing else'
              .format(name, sorted(moved), NPTH_DELTA_MM))


def main():
    bad = []
    for name, fn in sorted(globals().items()):
        if not name.startswith('test_'):
            continue
        print('--- {}'.format(name))
        try:
            fn()
        except Exception as exc:                              # noqa: BLE001
            bad.append('{}: {}: {}'.format(name, type(exc).__name__, exc))
            print('  FAIL: {}'.format(bad[-1]))
    if bad:
        print('\n{} FAILED'.format(len(bad)))
        return 1
    print('ALL PASS')
    return 0


if __name__ == '__main__':
    sys.exit(main())
