"""SWIG compatibility shims for KiCad's `pcbnew` python module (issue #795).

KiCad hand-writes the `__iter__` of the container classes whose items need a
`Cast()` -- `TRACKS` (`board.GetTracks()`), `DRAWINGS` (`board.GetDrawings()`,
`footprint.GraphicalItems()`) and `VECTOR_SHAPEPTR` -- and those generators
call the Python-2 spelling of the iterator step:

    def __iter__(self):
        it = self.iterator()
        try:
            while True:
                item = it.next()   # <-- py2 spelling
                yield item.Cast()
        except StopIteration:
            return

`SwigPyIterator` carried BOTH `next()` and `__next__()` until **SWIG 4.5.0**
(2026-08-06), whose py2 removal deleted the former and promoted the latter from
alias to the real method (swig commit da2f0f9c, "Python: Drop operators
compatibility"; the umbrella is swig/swig#3201). A KiCad whose `pcbnew.py` was
generated by SWIG >= 4.5.0 therefore raises

    AttributeError: 'SwigPyIterator' object has no attribute 'next'

the first time anything iterates a board's tracks or drawings.

**The variable is the SWIG that BUILT the package, not KiCad's version and not
the board.** The same KiCad 10.0.6 works or fails depending on the distro's SWIG,
which is why it reads as "it broke in the last few KiCad builds": Arch shipped
swig 4.5.0-1 on 2026-08-06 and every KiCad rebuilt after that is affected, while
distros still on 4.4.x are fine. Two other KiCad plugins (InteractiveHtmlBom
#563, SpinRender #17) hit it the same week, all on Arch.

Upstream KiCad still has the py2 spelling at 10.0.6 -- `pcbnew/python/swig/
board.i:114` (DRAWINGS) and `:128` (TRACKS), `common/swig/shape.i:155`
(VECTOR_SHAPEPTR) -- and there is no fix to wait for on master, because SWIG and
the whole python integration were REMOVED from master in 2026-03 (commit
65a442b1) in favour of the IPC API. Any upstream fix has to land on the 10.0
branch directly, so shim it here.

`patch_swig_iterators()` restores the alias on the class, which repairs every
call site in one place -- ours, KiCad's own python helpers, and any other plugin
in the process -- instead of rewriting ~40 `for t in board.GetTracks()` loops
into index walks and then finding the one that was missed. It is idempotent and
a no-op on a pcbnew whose SWIG still supplies `next`.
"""


def patch_swig_iterators(module=None):
    """Give `module.SwigPyIterator` back its py2 `next()` alias if it lacks one.

    `module` defaults to the imported `pcbnew`; pass one explicitly to patch a
    different SWIG module (or a stand-in, in tests). Returns True when this call
    installed the alias, False when there was nothing to do or nothing it could
    do (no pcbnew, no `SwigPyIterator`, no `__next__` to alias, or a class that
    refuses attribute assignment -- SWIG's `-builtin` mode, which KiCad does not
    use).

    Deliberately UNCACHED. It is called once per importing module (a handful of
    times per process) and costs ~0.04 ms when pcbnew is absent, so remembering
    the answer would buy nothing and cost a stale-state class of bug: a False
    cached from an early call could suppress a later, genuinely needed patch.
    Idempotent instead -- a second call sees the alias it installed and returns
    False, having done nothing.
    """
    if module is None:
        try:
            import pcbnew as module  # noqa: N813
        except Exception:
            return False
    cls = getattr(module, 'SwigPyIterator', None)
    if cls is None:
        return False
    if getattr(cls, 'next', None) is not None:
        return False            # this SWIG still ships the alias
    step = getattr(cls, '__next__', None)
    if step is None:
        return False            # nothing to alias it to; leave it alone
    try:
        cls.next = step
    except (AttributeError, TypeError):
        return False            # e.g. a builtin/immutable type
    return True
